//
//  CloudKit.h
//  ANAnimatedCloud
//
//  Created by Anna Bushmeleva on 26.12.16.
//  Copyright © 2016 (null). All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <UIKit/UIKit.h>



typedef enum : NSInteger
{
    CloudKitResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    CloudKitResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    CloudKitResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    CloudKitResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.

} CloudKitResizingBehavior;

extern CGRect CloudKitResizingBehaviorApply(CloudKitResizingBehavior behavior, CGRect rect, CGRect target);


@interface CloudKit : NSObject

// iOS Controls Customization Outlets
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* smallCloudIconTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* middleCloudIconTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* largeCloudIconTargets;
@property (strong, nonatomic) IBOutletCollection(NSObject) NSArray* sunIconTargets;

// Drawing Methods
+ (void)drawSunIcon;
+ (void)drawSunIconWithFrame: (CGRect)targetFrame resizing: (CloudKitResizingBehavior)resizing;

// Generated Images
+ (UIImage*)imageOfSmallCloudIcon;
+ (UIImage*)imageOfMiddleCloudIcon;
+ (UIImage*)imageOfLargeCloudIcon;
+ (UIImage*)imageOfSunIcon;

@end
